name       : libnfnetlink
version    : 1.0.1
release    : 1
source     :
    - ftp://ftp.netfilter.org/pub/libnfnetlink/libnfnetlink-1.0.1.tar.bz2 : f270e19de9127642d2a11589ef2ec97ef90a649a74f56cf9a96306b04817b51a
license    : GPL-2.0
component  : programming.library
summary    : libnfnetlink is the low-level library for netfilter related kernel/userspace communication.
description: |
    libnfnetlink provides a generic messaging infrastructure for in-kernel netfilter subsystems (such as nfnetlink_log, nfnetlink_queue, nfnetlink_conntrack) and their respective users and/or management tools in userspace. This library is not meant as a public API for application developers. It is only used by other netfilter.org projects, such as libnetfilter_log, libnetfilter_queue or libnetfilter_conntrack.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
